services:
  - type: web
    name: stirling-pdf
    env: docker
    plan: free
    region: oregon
    healthCheckPath: /
    envVars:
      - key: DOCKER_ENABLE_SECURITY
        value: "false"
      - key: APP_LOCALE
        value: "en_GB"
      - key: SYSTEM_DEFAULT_LOCALE
        value: "en_GB"
